---
- name: Download PHP source
  get_url:
    url: "{{ php_src_archive }}"
    dest: "/tmp/{{ php_version }}.tar.gz"

- name: Extract PHP source
  unarchive:
    src: "/tmp/{{ php_version }}.tar.gz"
    dest: /tmp
    copy: no

- name: Create configure script
  template:
    src: configure.sh.j2
    dest: "/tmp/{{ php_version }}/configure.sh"
    mode: 755

- name: Configure build
  command: ./configure.sh
  args:
    chdir: "/tmp/{{ php_version }}"

- name: Compile PHP
  command: make -j{{ ansible_processor_cores }}
  args:
    chdir: "/tmp/{{ php_version }}"

- name: Install PHP
  command: make install
  args:
    chdir: "/tmp/{{ php_version }}"
