---
- name: Download xdebug
  get_url:
    url: "{{ xdebug_src_archive }}"
    dest: "/tmp/xdebug.tgz"

- name: Extract xdebug source
  unarchive:
    src: "/tmp/xdebug.tgz"
    dest: /tmp
    copy: no

- name: Run phpize
  command: phpize
  args:
    chdir: "/tmp/{{ xdebug_version }}"

- name: Configure build
  command: ./configure
  args:
    chdir: "/tmp/{{ xdebug_version }}"

- name: Compile xdebug
  command: make -j{{ ansible_processor_cores }}
  args:
    chdir: "/tmp/{{ xdebug_version }}"

- name: Copy xdebug extension
  command: cp "/tmp/{{ xdebug_version }}/modules/xdebug.so" /usr/local/lib/php/extensions/no-debug-non-zts-20131226