---
- name: Download xdebug
  get_url:
    url: "{{ xdebug_src_archive }}"
    dest: "/tmp/xdebug.tgz"

- name: Extract xdebug source
  unarchive:
    src: "/tmp/xdebug.tgz"
    dest: /usr/local/src
    copy: no

- name: Run phpize
  command: phpize
  args:
    chdir: "/usr/local/src/xdebug-2.3.1"

- name: Configure build
  command: ./configure
  args:
    chdir: "/usr/local/src/xdebug-2.3.1"

- name: Compile xdebug
  command: make -j{{ ansible_processor_cores }}
  args:
    chdir: "/usr/local/src/xdebug-2.3.1"

- name: Copy xdebug extension
  command: cp /usr/local/src/xdebug-2.3.1/modules/xdebug.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226