---
- name: Enable php-fpm
  service:
    name: php-fpm
    enabled: yes

- name: Start php-fpm
  service:
    name: php-fpm
    state: started

- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted
