---
  - name: Add nodejs repository
    apt_repository:
      repo: ppa:chris-lea/node.js
      state: present
      update_cache: yes

  - name: Install nodejs
    apt:
      pkg: nodejs
      state: present
